import { gettext, ngettext } from "./i18n";

// Generated by scripts/extract-i18n-messages.mjs.
// Keep TSX strings visible to Django's JavaScript message extractor.
void [
  gettext("Markdown + LaTeX"), // static/ts/components/ContentEditor.tsx
  gettext("Delete attachment \"%(name)s\"?"), // static/ts/components/ContentEditor.tsx
  gettext("Deleting the attachment failed."), // static/ts/components/ContentEditor.tsx
  gettext("Uploading attachments failed."), // static/ts/components/ContentEditor.tsx
  gettext("This attachment belongs to a different content item."), // static/ts/components/ContentEditor.tsx
  gettext("Input format help"), // static/ts/components/ContentEditor.tsx
  gettext("Uploading..."), // static/ts/components/ContentEditor.tsx
  gettext("Upload attachments"), // static/ts/components/ContentEditor.tsx
  gettext("file"), // static/ts/components/ContentEditor.tsx
  gettext("Append to text"), // static/ts/components/ContentEditor.tsx
  gettext("Delete"), // static/ts/components/ContentEditor.tsx
  gettext("Select all"), // static/ts/components/ListProblemPicker.ts
  gettext("Problem"), // static/ts/components/ListProblemPicker.ts
  gettext("Source"), // static/ts/components/ListProblemPicker.ts
  gettext("Tags"), // static/ts/components/ListProblemPicker.ts
  gettext("Add selected"), // static/ts/components/ListProblemPicker.ts
  gettext("In list"), // static/ts/components/ListProblemPicker.ts
  gettext("Search failed."), // static/ts/components/ListProblemPicker.ts
  gettext("No matching problems."), // static/ts/components/ListProblemPicker.ts
  gettext("PDF could not be loaded."), // static/ts/components/PdfPreview.tsx
  gettext("Loading PDF..."), // static/ts/components/PdfPreview.tsx
  gettext("No problems transcribed."), // static/ts/components/ProblemDraftEditor.tsx
  gettext("Invalid response"), // static/ts/components/ProblemDraftEditor.tsx
  gettext("Tag suggestion failed"), // static/ts/components/ProblemDraftEditor.tsx
  gettext("Network error during tag suggestion"), // static/ts/components/ProblemDraftEditor.tsx
  gettext("Suggesting tags..."), // static/ts/components/ProblemDraftEditor.tsx
  gettext("Autosuggest tags"), // static/ts/components/ProblemDraftEditor.tsx
  gettext("Problem %(number)s."), // static/ts/components/ProblemDraftEditor.tsx
  gettext("Solved"), // static/ts/components/StatusCells.ts
  gettext("Bookmarked"), // static/ts/components/StatusCells.ts
  gettext("Liked"), // static/ts/components/StatusCells.ts
  gettext("Notes"), // static/ts/components/StatusCells.ts
  gettext("Add tag..."), // static/ts/components/TagPicker.tsx
  gettext("NEW"), // static/ts/components/TagPicker.tsx
  gettext("Save failed"), // static/ts/list-bulk-edit.tsx
  gettext("Network error during save"), // static/ts/list-bulk-edit.tsx
  gettext("No problems yet."), // static/ts/list-bulk-edit.tsx
  gettext("Saving problems..."), // static/ts/list-bulk-edit.tsx
  gettext("Save changes"), // static/ts/list-bulk-edit.tsx
  gettext("Back"), // static/ts/list-bulk-edit.tsx
  gettext("Transcription failed: %(error)s"), // static/ts/pdf-import.tsx
  gettext("unknown error"), // static/ts/pdf-import.tsx
  gettext("Choose a source before importing."), // static/ts/pdf-import.tsx
  gettext("Network error during transcription"), // static/ts/pdf-import.tsx
  gettext("Request failed"), // static/ts/pdf-import.tsx
  gettext("Transcription failed"), // static/ts/pdf-import.tsx
  gettext("Discard this import? Your edits will be lost."), // static/ts/pdf-import.tsx
  gettext("Import failed"), // static/ts/pdf-import.tsx
  gettext("Network error during import"), // static/ts/pdf-import.tsx
  gettext("Select a PDF file to import problems from."), // static/ts/pdf-import.tsx
  gettext("Drop PDF here"), // static/ts/pdf-import.tsx
  gettext("or click to choose a file"), // static/ts/pdf-import.tsx
  gettext("Deselect all"), // static/ts/pdf-import.tsx
  gettext("Transcribe selected pages"), // static/ts/pdf-import.tsx
  gettext("Queued..."), // static/ts/pdf-import.tsx
  gettext("Transcribing selected pages..."), // static/ts/pdf-import.tsx
  gettext("Starting transcription..."), // static/ts/pdf-import.tsx
  gettext("Cancel"), // static/ts/pdf-import.tsx
  gettext("Resumed from a previous session; re-upload the PDF to see it alongside the problems."), // static/ts/pdf-import.tsx
  gettext("PDF not loaded."), // static/ts/pdf-import.tsx
  gettext("Back to page selection"), // static/ts/pdf-import.tsx
  gettext("Review & import"), // static/ts/pdf-import.tsx
  gettext("Cancel import"), // static/ts/pdf-import.tsx
  gettext("Please check the details below. Click Confirm to import, or Back to keep editing."), // static/ts/pdf-import.tsx
  gettext("The whole PDF will be attached to %(source)s, %(year)s."), // static/ts/pdfImport/components.tsx
  gettext("The whole PDF will be attached to %(source)s."), // static/ts/pdfImport/components.tsx
  gettext("Choose a source to decide where the whole PDF will be attached."), // static/ts/pdfImport/components.tsx
  gettext("-- Select source --"), // static/ts/pdfImport/components.tsx
  gettext("New source"), // static/ts/pdfImport/components.tsx
  gettext("Year"), // static/ts/pdfImport/components.tsx
  gettext("e.g. 2024"), // static/ts/pdfImport/components.tsx
  gettext("Language"), // static/ts/pdfImport/components.tsx
  gettext("hr or en"), // static/ts/pdfImport/components.tsx
  gettext("Tags for all problems"), // static/ts/pdfImport/components.tsx
  gettext("Save whole PDF"), // static/ts/pdfImport/components.tsx
  gettext("PDF source URL"), // static/ts/pdfImport/components.tsx
  gettext("Could not create source."), // static/ts/pdfImport/components.tsx
  gettext("Network error while creating source."), // static/ts/pdfImport/components.tsx
  gettext("Name (EN)"), // static/ts/pdfImport/components.tsx
  gettext("Name (HR)"), // static/ts/pdfImport/components.tsx
  gettext("Slug"), // static/ts/pdfImport/components.tsx
  gettext("Parent"), // static/ts/pdfImport/components.tsx
  gettext("-- No parent --"), // static/ts/pdfImport/components.tsx
  gettext("Creating source..."), // static/ts/pdfImport/components.tsx
  gettext("Create source"), // static/ts/pdfImport/components.tsx
  gettext("OCR"), // static/ts/pdfImport/components.tsx
  gettext("LLM cleanup"), // static/ts/pdfImport/components.tsx
  gettext("Running"), // static/ts/pdfImport/components.tsx
  gettext("Done"), // static/ts/pdfImport/components.tsx
  gettext("Failed"), // static/ts/pdfImport/components.tsx
  gettext("Pending"), // static/ts/pdfImport/components.tsx
  gettext("The whole PDF will be saved for %(source)s, %(year)s."), // static/ts/pdfImport/components.tsx
  gettext("(none)"), // static/ts/pdfImport/components.tsx
  gettext("The whole PDF will be saved for %(source)s."), // static/ts/pdfImport/components.tsx
  gettext("Original PDF"), // static/ts/pdfImport/components.tsx
  gettext("The original PDF will not be saved."), // static/ts/pdfImport/components.tsx
  ngettext("%(count)s unsaved change", "%(count)s unsaved changes", 2), // static/ts/components/ListProblemPicker.ts
  ngettext("%(count)s problem", "%(count)s problems", 2), // static/ts/components/ListProblemPicker.ts
  ngettext("%(count)s page", "%(count)s pages", 2), // static/ts/pdf-import.tsx
  ngettext("Transcribe %(count)s page", "Transcribe %(count)s pages", 2), // static/ts/pdf-import.tsx
  ngettext("Confirm - import %(count)s problem and save PDF", "Confirm - import %(count)s problems and save PDF", 2), // static/ts/pdf-import.tsx
  ngettext("Confirm - import %(count)s problem", "Confirm - import %(count)s problems", 2), // static/ts/pdf-import.tsx
];
