# Generated by Django 6.0.3 on 2026-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0002_source_created_by_source_group_source_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="group",
        ),
        migrations.RemoveField(
            model_name="source",
            name="visibility",
        ),
        migrations.AddField(
            model_name="source",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
