# Generated by Django 6.0.3 on 2026-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_sourcedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcedocument',
            options={'ordering': [models.OrderBy(models.F('year'), descending=True, nulls_last=True), 'original_filename', 'id']},
        ),
    ]
