# Generated by Django 6.0.5 on 2026-06-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0005_alter_sourcedocument_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedocument",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
