# Generated by Django 6.0.3 on 2026-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_remove_problemlist_public_remove_problemlist_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problemlist",
            name="group",
        ),
        migrations.RemoveField(
            model_name="problemlist",
            name="visibility",
        ),
        migrations.AddField(
            model_name="problemlist",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
