# Generated by Django 6.0.3 on 2026-03-12 20:50

from django.db import migrations


def create_personal_groups(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Group = apps.get_model("groups", "Group")
    GroupMembership = apps.get_model("groups", "GroupMembership")

    for user in User.objects.filter(personal_group__isnull=True):
        group = Group.objects.create(
            name=user.username,
            slug=f"user-{user.pk}",
            personal=True,
        )
        GroupMembership.objects.create(
            group=group,
            user=user,
            role="admin",
        )
        user.personal_group = group
        user.save(update_fields=["personal_group"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_personal_group"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_personal_groups, migrations.RunPython.noop),
    ]
