FROM docker.io/ubuntu:16.04

# WARNING: DEBIAN_FRONTEND=noninteractive disables the root password prompt of
# mysql-server installation. That means the root password will be empty! Do NOT
# use in production!

# subversion (svn): used to install jquery-star-rating-plugin
RUN set -ex \
        && apt-get update \
        && (DEBIAN_FRONTEND=noninteractive apt-get install -y \
            mysql-client-core-5.7 \
            mysql-server-5.7) \
        && DEBIAN_FRONTEND=noninteractive apt-get install -y \
            gettext \
            git \
            libmysqlclient-dev \
            memcached \
            python-pip \
            python-setuptools \
            python2.7-dev \
            ruby-dev \
            subversion \
        && apt-get clean

# - lmodern and textlive-fonts-recommended are both required by our LaTex template.
# - texlive-lang-european is required for \usepackage[croatian]{babel}.
#   In principle, we could remove this line instead.
# - dvipng is used to convert latex output to pngs.
RUN set -ex \
        && apt-get update \
        && apt-get install -y --no-install-recommends \
            texlive-latex-extra \
            texlive-lang-european \
            texlive-fonts-recommended \
            lmodern \
            dvipng \
        && apt-get clean

# These are the latest versions of pip and setuptools that support Python 2.
RUN python2 -m pip install --upgrade \
        pip==20.3.4 \
        setuptools==44.0.0
COPY requirements.txt /tmp/

RUN python2 -m pip install -r /tmp/requirements.txt \
        && python2 -m pip cache purge

# Install nodejs and npm. 10.24.1 seems to be the oldest version for which `npm install` succeeds.
SHELL ["/bin/bash", "-ec"]
RUN curl -o /tmp/nvm-install.sh https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh \
    && echo "8e45fa547f428e9196a5613efad3bfa4d4608b74ca870f930090598f5af5f643  /tmp/nvm-install.sh" | sha256sum -c \
    && bash /tmp/nvm-install.sh \
    && rm /tmp/nvm-install.sh \
    && source /root/.nvm/nvm.sh \
    && nvm install 10.24.1
