# Generated by Django 6.0.3 on 2026-03-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("topic", "Topic"),
                            ("technique", "Technique"),
                            ("meta", "Meta"),
                        ],
                        max_length=16,
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                ("translations", models.JSONField(default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
    ]
