# Generated by Django 6.0.3 on 2026-05-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_tag_descriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="short_translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
