# Generated by Django 6.0.3 on 2026-03-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sources", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("problem_number", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("expected_answer", models.JSONField(blank=True, null=True)),
                ("original_language", models.CharField(default="en", max_length=10)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problems",
                        to="sources.source",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="tags.tag")),
            ],
            options={
                "ordering": ["source", "year", "problem_number"],
            },
        ),
    ]
