# Generated by Django 6.0.3 on 2026-03-12 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("group", "Group"), ("draft", "Draft")],
                default="public",
                max_length=10,
            ),
        ),
    ]
