# Generated by Django 6.0.3 on 2026-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_problem_created_by_problem_group_problem_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="group",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="visibility",
        ),
        migrations.AddField(
            model_name="problem",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
