# Generated by Django 6.0.3 on 2026-04-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_remove_problem_group_remove_problem_visibility_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="slug",
        ),
    ]
