# Generated by Django 6.0.3 on 2026-04-11 21:00

import django.db.models.deletion
import skoljka.apps.importer.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pdf_ciphertext", models.BinaryField()),
                ("pages_json", models.TextField(default="[]")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("result_ciphertext", models.BinaryField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=skoljka.apps.importer.models._default_expires_at
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="importer_tr_user_id_879edb_idx"
                    ),
                    models.Index(
                        fields=["status", "updated_at"],
                        name="importer_tr_status_17365a_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="importer_tr_expires_429661_idx"
                    ),
                ],
            },
        ),
    ]
