# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptionjob",
            name="source_context_json",
            field=models.TextField(default="{}"),
        ),
    ]
