# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0002_transcriptionjob_source_context_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptionjob",
            name="progress_json",
            field=models.TextField(default='{"current":null,"steps":[]}'),
        ),
    ]
