# Generated by Codex on 2026-05-13

import skoljka.apps.importer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0003_transcriptionjob_progress_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptionjob",
            name="original_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=skoljka.apps.importer.models.original_pdf_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="transcriptionjob",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
